[2025-08-27T05:00:40.725+0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T05:00:40.733+0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_pipeline.extract_task scheduled__2025-08-26T00:00:00+00:00 [queued]>
[2025-08-27T05:00:40.736+0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_pipeline.extract_task scheduled__2025-08-26T00:00:00+00:00 [queued]>
[2025-08-27T05:00:40.736+0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-27T05:00:40.742+0500] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2025-08-26 00:00:00+00:00
[2025-08-27T05:00:40.750+0500] {standard_task_runner.py:63} INFO - Started process 60062 to run task
[2025-08-27T05:00:40.753+0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_csv_pipeline', 'extract_task', 'scheduled__2025-08-26T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_csv_pipeline.py', '--cfg-path', '/var/folders/qd/tg0x144j35g7_hrcjsdscnrw0000gn/T/tmp7hujyzdw']
[2025-08-27T05:00:40.754+0500] {standard_task_runner.py:91} INFO - Job 9: Subtask extract_task
[2025-08-27T05:00:40.780+0500] {task_command.py:426} INFO - Running <TaskInstance: etl_csv_pipeline.extract_task scheduled__2025-08-26T00:00:00+00:00 [running]> on host devs-macbook-pro-16.local
[2025-08-27T05:00:40.819+0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='junaidiqbalshah011@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_csv_pipeline' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-26T00:00:00+00:00'
[2025-08-27T05:00:40.819+0500] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T05:00:40.821+0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T05:00:40.821+0500] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/dev/Desktop/workspace/Data-Engineering/Apache-Airflow/Day-01/dags/etl_csv_pipeline.py", line 9, in extract
    df = pd.read_csv('/path/to/input.csv')
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/input.csv'
[2025-08-27T05:00:40.843+0500] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_csv_pipeline, task_id=extract_task, run_id=scheduled__2025-08-26T00:00:00+00:00, execution_date=20250826T000000, start_date=20250827T000040, end_date=20250827T000040
[2025-08-27T05:00:40.847+0500] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task extract_task ([Errno 2] No such file or directory: '/path/to/input.csv'; 60062)
[2025-08-27T05:00:40.867+0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-27T05:00:40.877+0500] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T05:00:40.878+0500] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-27T22:41:34.131+0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-27T22:41:34.139+0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_csv_pipeline.extract_task scheduled__2025-08-26T00:00:00+00:00 [queued]>
[2025-08-27T22:41:34.142+0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_csv_pipeline.extract_task scheduled__2025-08-26T00:00:00+00:00 [queued]>
[2025-08-27T22:41:34.142+0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-27T22:41:34.148+0500] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2025-08-26 00:00:00+00:00
[2025-08-27T22:41:34.154+0500] {standard_task_runner.py:63} INFO - Started process 74240 to run task
[2025-08-27T22:41:34.157+0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_csv_pipeline', 'extract_task', 'scheduled__2025-08-26T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_csv_pipeline.py', '--cfg-path', '/var/folders/qd/tg0x144j35g7_hrcjsdscnrw0000gn/T/tmpk_h1zni4']
[2025-08-27T22:41:34.158+0500] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_task
[2025-08-27T22:41:34.181+0500] {task_command.py:426} INFO - Running <TaskInstance: etl_csv_pipeline.extract_task scheduled__2025-08-26T00:00:00+00:00 [running]> on host devs-macbook-pro-16.local
[2025-08-27T22:41:34.212+0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='junaidiqbalshah011@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_csv_pipeline' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-26T00:00:00+00:00'
[2025-08-27T22:41:34.213+0500] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-27T22:41:37.058+0500] {logging_mixin.py:188} INFO - Extracted data
[2025-08-27T22:41:37.061+0500] {python.py:237} INFO - Done. Returned value was: None
[2025-08-27T22:41:37.062+0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-27T22:41:37.064+0500] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_csv_pipeline, task_id=extract_task, run_id=scheduled__2025-08-26T00:00:00+00:00, execution_date=20250826T000000, start_date=20250827T174134, end_date=20250827T174137
[2025-08-27T22:41:37.091+0500] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-27T22:41:37.107+0500] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-27T22:41:37.107+0500] {local_task_job_runner.py:222} INFO - ::endgroup::
